{{- if .Values.secman }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secman
  labels:
    {{- include "default.labels" . | indent 4 }}
  annotations:
    deploymentTime: {{ now | date "02.01.2006 15:04:05" }}
data:
  config-init.hcl: |
    auto_auth {
      method {
        type = "kubernetes"
        namespace = "{{ .Values.secman.namespace }}"
        mount_path = "auth/os/{{ .Values.secman.cluster }}"
        config { 
          role = "{{ .Values.secman.role }}" 
        }
      }
      
      sink {
        type = "file"
        config { 
          path = "/home/vault/.vault-token" 
        }
      }
    }

    exit_after_auth = true
    pid_file = "/home/vault/.pid"

    vault { 
      address = "{{ .Values.secman.address }}"
    }

{{- $secretPath := printf "%s/%s" .Values.secman.namespace .Values.secman.path }}

{{- range .Values.secman.secretText }}
    template = {
      source = "/vault/configs/{{ .name }}.ctmpl"
      destination = "/vault/secrets/{{ .name }}"
      left_delimiter = "(("
      right_delimiter = "))"
    }
{{- end }}

{{- range .Values.secman.secretFile }}
    template = {
      source = "/vault/configs/{{ .name }}.ctmpl"
      destination = "/vault/secrets/{{ .name }}"
      left_delimiter = "(("
      right_delimiter = "))"
    }
{{- end }}

{{- range .Values.secman.secretText }}
  {{ .name }}.ctmpl: |
    ((- with secret "{{ $secretPath }}/{{ .secret }}" -))
    (( (index .Data "{{ .name }}") ))
    ((- end -))
{{- end }}

{{- range .Values.secman.secretFile }}
  {{ .name }}.ctmpl: |
    ((- with secret "{{ $secretPath }}/{{ .secret }}" -))
    (( base64Decode (index .Data "{{ .name }}") ))
    ((- end -))
{{- end }}
{{- end }}