FROM redhat.registry-ci.delta.sbrf.ru/ubi8/s2i-core@sha256:1cc2b814e82c3fb345774774da3480adede53b1d12a25275e0416ad816b8e28d

COPY docker/debezium-connector-postgres-1.8.1.Final-plugin.tar.gz /data/connect-jars
COPY docker/confluentinc-kafka-connect-jdbc-10.7.0.tar.gz /data/connect-jars