-- !!! Для применения этого скрипта нужно удалить папку postgres-data-source. !!!

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE table_a (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation TEXT,
    b_id BIGINT,
    c_id BIGINT
);

CREATE TABLE table_b (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     correlation TEXT,
     a_id BIGINT NOT NULL,
     c_id BIGINT
);

CREATE TABLE table_c (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     correlation TEXT,
     a_id BIGINT NOT NULL,
     b_id BIGINT NOT NULL
);

ALTER TABLE table_a ADD CONSTRAINT fk_b_table FOREIGN KEY(b_id) REFERENCES table_b(id);
ALTER TABLE table_a ADD CONSTRAINT fk_c_table FOREIGN KEY(c_id) REFERENCES table_c(id);

ALTER TABLE table_b ADD CONSTRAINT fk_a_table FOREIGN KEY(a_id) REFERENCES table_a(id);
ALTER TABLE table_b ADD CONSTRAINT fk_c_table FOREIGN KEY(c_id) REFERENCES table_c(id);

ALTER TABLE table_c ADD CONSTRAINT fk_a_table FOREIGN KEY(a_id) REFERENCES table_a(id);
ALTER TABLE table_c ADD CONSTRAINT fk_b_table FOREIGN KEY(b_id) REFERENCES table_b(id);

INSERT INTO customers (name) VALUES ('joe'), ('bob'), ('sue');

CREATE OR REPLACE FUNCTION update_change_source()
    RETURNS TRIGGER AS
$$
BEGIN
    -- Заполняем новое поле change_source значением PRIMARY только в том случае, если оно пришло из primary
    IF NEW.change_source = 'DEBEZIUM' THEN
        NEW.change_source = 'STANDIN';
    ELSE
        NEW.change_source = 'PRIMARY';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION create_change_source_and_reset_seqs_triggers()
    RETURNS VOID AS
$$
DECLARE
    tbl_name    text;
    schema_name text := "current_schema"();
BEGIN
    -- Выбор таблиц, которым нужно проставить change_source - все таблицы из схемы, кроме таблиц liquibase
    FOR tbl_name IN SELECT table_name
                    FROM information_schema.tables
                    WHERE table_schema = schema_name
                      AND table_name <> 'databasechangelog'
                      AND table_name <> 'databasechangeloglock'
        LOOP
            -- Добавление колонки change_source со значением по умолчанию PRIMARY
            EXECUTE format('ALTER TABLE %s ADD COLUMN IF NOT EXISTS change_source TEXT default ''PRIMARY'';', tbl_name);

            -- Пересоздание триггера на зополнение колонки change_source при инсерте или апдейте
            EXECUTE format('DROP TRIGGER IF EXISTS trigger_change_source_%s on %s', tbl_name, tbl_name);
            EXECUTE format(
                    'CREATE TRIGGER trigger_change_source_%s BEFORE INSERT OR UPDATE ON %s FOR EACH ROW EXECUTE FUNCTION update_change_source()',
                    tbl_name, tbl_name);
        END LOOP;
END
$$ LANGUAGE plpgsql;

SELECT create_change_source_and_reset_seqs_triggers();