-- !!! Для применения этого скрипта нужно удалить папку postgres-data-source. !!!

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

alter sequence customers_id_seq RESTART WITH 1000000000;

CREATE TABLE table_a (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation TEXT,
    b_id BIGINT,
    c_id BIGINT
);

alter sequence table_a_id_seq RESTART WITH 1000000000;

CREATE TABLE table_b (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     correlation TEXT,
     a_id BIGINT NOT NULL,
     c_id BIGINT
);

alter sequence table_b_id_seq RESTART WITH 1000000000;

CREATE TABLE table_c (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     correlation TEXT,
     a_id BIGINT NOT NULL,
     b_id BIGINT NOT NULL
);

alter sequence table_b_id_seq RESTART WITH 1000000000;

ALTER TABLE table_a ADD CONSTRAINT fk_b_table FOREIGN KEY(b_id) REFERENCES table_b(id);
ALTER TABLE table_a ADD CONSTRAINT fk_c_table FOREIGN KEY(c_id) REFERENCES table_c(id);

ALTER TABLE table_b ADD CONSTRAINT fk_a_table FOREIGN KEY(a_id) REFERENCES table_a(id);
ALTER TABLE table_b ADD CONSTRAINT fk_c_table FOREIGN KEY(c_id) REFERENCES table_c(id);

ALTER TABLE table_c ADD CONSTRAINT fk_a_table FOREIGN KEY(a_id) REFERENCES table_a(id);
ALTER TABLE table_c ADD CONSTRAINT fk_b_table FOREIGN KEY(b_id) REFERENCES table_b(id);

CREATE OR REPLACE FUNCTION update_change_source()
    RETURNS TRIGGER AS
$$
BEGIN
    -- Заполняем новое поле change_source значением STANDIN только если изменения из standin
    IF NEW.change_source = 'DEBEZIUM' THEN
        NEW.change_source = 'PRIMARY';
    ELSE
        NEW.change_source = 'STANDIN';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION create_change_source_and_reset_seqs_triggers()
    RETURNS VOID AS
$$
DECLARE
    tbl_name            text;
    sequence_curr_value bigint;
    schema_name         text := "current_schema"();
    id_seq_exists       bool;
BEGIN
    -- Выбор таблиц, которым нужно проставить change_source - все таблицы из схемы, кроме таблиц liquibase
    FOR tbl_name IN SELECT table_name
                    FROM information_schema.tables
                    WHERE table_schema = schema_name
                      AND table_name <> 'databasechangelog'
                      AND table_name <> 'databasechangeloglock'
        LOOP
            -- Добавление колонки change_source со значением по умолчанию STANDIN
            EXECUTE format('ALTER TABLE %s ADD COLUMN IF NOT EXISTS change_source TEXT default ''STANDIN'';', tbl_name);

            -- Пересоздание триггера на зополнение колонки change_source при инсерте или апдейте
            EXECUTE format('DROP TRIGGER IF EXISTS trigger_change_source_%s on %s', tbl_name, tbl_name);
            EXECUTE format(
                    'CREATE TRIGGER trigger_change_source_%s BEFORE INSERT OR UPDATE ON %s FOR EACH ROW EXECUTE FUNCTION update_change_source()',
                    tbl_name, tbl_name);

            -- Проверка наличия id sequence у текущей таблицы
            EXECUTE format('SELECT 0 FROM pg_class where relname = ''%s_id_seq''', tbl_name) INTO id_seq_exists;
            IF id_seq_exists IS NOT NULL THEN
                -- Проверка и сдвиг сиквенса
                EXECUTE 'SELECT last_value FROM ' || tbl_name || '_id_seq;' INTO sequence_curr_value;
                IF sequence_curr_value < 100000000000 THEN
                    EXECUTE format('ALTER SEQUENCE %s_id_seq RESTART WITH 100000000000;', tbl_name);
                END IF;
            END IF;
        END LOOP;
END
$$ LANGUAGE plpgsql;

SELECT create_change_source_and_reset_seqs_triggers();

CREATE OR REPLACE FUNCTION update_hibernate_sequence()
    RETURNS VOID AS
$$
DECLARE
    sequence_curr_value bigint;
BEGIN
    -- Создание сиквенса для hibernate со сдвигом
    EXECUTE 'CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START 100000000000;';

    -- Если сиквенс уже есть, то сдвигаем его при необходимости
    EXECUTE 'SELECT last_value FROM hibernate_sequence' INTO sequence_curr_value;
    IF sequence_curr_value < 100000000000 THEN
        EXECUTE 'ALTER SEQUENCE hibernate_sequence RESTART WITH 100000000000;';
    END IF;
END
$$ LANGUAGE plpgsql;

SELECT update_hibernate_sequence();